version: '3.8'

services:
  your-service-name:
    image: ml-model
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: uvicorn apps.app:app --host 0.0.0.0 --port 8000
